-- 코드를 입력하세요
SELECT FH.FLAVOR
FROM FIRST_HALF AS FH
INNER JOIN ICECREAM_INFO AS IC
ON FH.FLAVOR = IC.FLAVOR
WHERE FH.TOTAL_ORDER > 3000
AND IC.INGREDIENT_TYPE = 'fruit_based'
ORDER BY FH.TOTAL_ORDER DESC